project:
  type: website
  output-dir: _site

website:
  title: "PHC 6701: R for Data Science"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: lessons/lesson01_greater_data_science.qmd
      - href: lessons/lesson02_introduction_to_R.qmd
      - href: lessons/lesson02s_scripts.qmd
      - href: lessons/lesson03_introduction_to_Quarto.qmd
      - href: lessons/lesson04_ggplot.qmd
      - href: lessons/lesson04s_examples.qmd
      - href: lessons/lesson05_RStudio_projects.qmd
      - href: lessons/lesson06_atomic_vectors.qmd
      - href: lessons/lesson07_lists_and_tibbles.qmd
      - href: lessons/lesson08_Data_Read_Write.qmd
      - href: lessons/lesson09_dplyr.qmd
      - href: lessons/lesson09s_dplyr_v_base.qmd
      - href: lessons/lesson10_stringr.qmd
      - href: lessons/lesson11_functions.qmd
      - href: lessons/lesson12_purrr.qmd
      - href: lessons/lesson13_eda_w_tidyverse.qmd
      - href: lessons/lesson14_github.qmd
      - href: lessons/lesson00_preassessment.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

